server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${EXPERT_DB_URL:localhost}:5432/expertconsultation?serverTimezone=Europe/Bucharest&characterEncoding=UTF-8
    username: postgres
    password: ${EXPERT_DB_PASSWORD:root}
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
storage:
  filesystem:
    directory: expert_consultation_uploads
