version: "3.7"

services:
  postgres:
    container_name: expert-consultation-postgres
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '${EXPERT_DB_PASSWORD}'
      POSTGRES_DB: 'expertconsultation'
    volumes:
      - postgres-vol:/var/lib/postgresql/data

volumes:
  postgres-vol:
